#!/usr/bin/env bash
### EDIT THIS!! ##############################################################
# make sure this is the profile you will be using the extension with

##############################################################################

if [ -f deploy.cfg ];
    then 
        . deploy.cfg
    else
        echo "You need to create a 'deploy.cfg' file, based on deploy.cfg.template"
        exit 2
fi

THE_POLY_HEAP="polymlext.polyml-heap"

#the directory of the extension
extension="$(dirname $0)"
cd "$extension"
extension=`pwd`

#update the extension file and move it to firefox profile
echo "$extension/polymlext" > polymlext@ed.ac.uk
cp polymlext@ed.ac.uk "$FIREFOX_PROFILE/extensions/"
rm polymlext@ed.ac.uk

#remove these files to make firefox reregister the updated components
if [ -e "$FIREFOX_PROFILE/xpti.dat" ]; then rm "$FIREFOX_PROFILE/xpti.dat"; fi
if [ -e "$FIREFOX_PROFILE/compreg.dat" ]; then rm "$FIREFOX_PROFILE/compreg.dat"; fi

#if run is passed as a parameter run firefox
if [ "$1" == "run" ]; then $FIREFOX_BINARY -jsconsole; fi

#if package is passed as a parameter create the xpi package
if [ "$1" == "package" ]
    then
        #remove the isaplib heap
        isaplib_heap="$extension/polymlext/poly/isaplib/heaps/all.polyml-heap"
        if [ -e "$isaplib_heap" ]; then
            rm "$isaplib_heap";
        fi
        #remove the polyml heap
        polyml_heap="$extension/polymlext/poly/bin/$THE_POLY_HEAP"
        if [ -e "$polyml_heap" ]; then
            rm "$polyml_heap"
        fi
        #remove the packaged extension
        if [ -e polymlext.xpi ]; then
            rm polymlext.xpi;
        fi
        
        ZIP=`which zip`
        cd polymlext
        ${ZIP} -r ../polymlext.xpi *
        cd ..
fi
